[username]
format = '[╭─$user](cyan)'
show_always = true

[hostname]
ssh_only = false
format = '[@](white)[$hostname](blue)[: ](white)'

[directory]
style = 'cyan'

[git_status]
deleted = 'x'

[cmd_duration]
format = '[$duration](white)'

[time]
format = "[󰣇 ](cyan)[$time](white)\n"
time_format = '%r'
disabled = false

[character]
success_symbol = '[╰─](cyan)'
error_symbol = '[╰─](cyan)[󰰱](red)'
